### ISSUE TITLE
Timing of buzzer / game clock start

### ISSUE THREAD

**Issue by jroelofs** [Navisjon/uwh-refbox#1]
Game clock starts counting down at the end of the buzzing sound, but really it should happen at the beginning.

**Comment by garious** [comment]
Is this a bug in uwh-display, not uwh-refbox?

**Comment by jroelofs** [comment]
Definitely a ref-box bug.

The red box controls the buzzer circuitry, and the way it's currently set
up, it turns on the buzzer, waits, turns off the buzzer, then starts the
clock.

Ideally that should be: start the buzzer, start a timer whose action is
"stop the buzzer", then start the clock.

**Comment by jroelofs** [comment]
Looking at 'gong_clicked()', I think this has been partially fixed, by
changing the order of clock start w.r.t. flipping the buzzer pin / sleep /
flipping it back.

Now it has been turned into a UI blocking problem: clicking the gong button
blocks the ui thread from making progress while the sound is happening.
