### ISSUE TITLE
ref timeout triggers stack leak

### ISSUE THREAD

**Issue by garious** [Navisjon/uwh-refbox#3]
Looks like the calls to `mainloop` create a stackframe that is never cleaned up. Some evidence, on macOS, you can kill the app by pressing ctrl-c twice. After a ref timeout, you need to press it 4 times. After using the app for a while, there are so many stack frames, you can ctrl-c dozens of times and still not exit the app. This may be the reason the app freezes after 5-10 games.

**Comment by jroelofs** [comment]
Good catch!

**Comment by jroelofs** [comment]
I think the bug is here:

```python
def edit_continuation(self):
    def submit_clicked(game_clock):
        self.mgr.setGameClock(max(game_clock, 0))
        self.ref_timeout_clicked(save_state=False) # <----

    def cancel_clicked(game_clock):
        self.mgr.setGameClock(max(clock_at_pause, 0))
        self.ref_timeout_clicked(save_state=False) # <----
```

instead of returning back to the existing ref time out picker, it creates another one.
