### ISSUE TITLE
Game state change isn't intuitive when time is manually zeroed

### ISSUE THREAD

**Issue by jroelofs** [Navisjon/uwh-refbox#32]
Four different cases:

  1) Clock running, time zeroed via dialog
  1) Clock stopped, time zeroed via dialog
  1) Clock running, dialog opened but clock runs out naturally
  1) Clock running, clock runs out naturally

**Comment by garious** [comment]
I'll fix all this up. Case 3 there is really busted. If time runs out naturally while the dialog is open, and the user submits the change anyway, the time in the following half will change. If the user had set the time to zero, the half will be skipped entirely.

**Comment by garious** [comment]
Fixed in #33. Now option 4 is the only case that changes the game state.
